<a href="https://colab.research.google.com/github/aditya01ad/colab_codes/blob/main/notebooks/OR_Prep/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy — OR Analyst Prep
**Plan:** 5-Month OR Analyst | Foundation Sprint | Week 1–2
**Goal:** NumPy arrays and operations for OR data work

Topics: ndarray, indexing, broadcasting, linear algebra, aggregations, random, cost matrices

In [1]:
import numpy as np


## Array Creation

In [11]:
## np.array, np.zeros, np.ones, np.arange, np.linspace

# array
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a * 2)       # vectorized — no loop needed
print(a ** 2)
print(np.sum(a))
print(np.mean(a))

print("------------------------------")
# 2D array
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print(M.shape)     # (2, 3)
print(M[0])        # first row
print(M[:, 1])     # second column
print(M.T)         # transpose

print("------------------------------")
# Some matrises
print(np.zeros((3, 3)))
print((np.ones((2, 4))))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

print("------------------------------")

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
15
3.0
------------------------------
(2, 3)
[1 2 3]
[2 5]
[[1 4]
 [2 5]
 [3 6]]
------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
------------------------------


## Indexing & Reshaping

In [3]:
# Slicing, fancy indexing, reshape


## Operations & Broadcasting

In [4]:
# Arithmetic, broadcasting rules


## Linear Algebra

In [5]:
# dot product, matmul, np.linalg.inv, np.linalg.eig


## OR Practice — Cost Matrix

In [6]:
# Build a cost matrix, find min cost row/col
