<a href="https://colab.research.google.com/github/aditya01ad/colab_codes/blob/main/notebooks/OR_Prep/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy — OR Analyst Prep
**Plan:** 5-Month OR Analyst | Foundation Sprint | Week 1–2
**Goal:** NumPy arrays and operations for OR data work

Topics: ndarray, indexing, broadcasting, linear algebra, aggregations, random, cost matrices

In [2]:
import numpy as np


## Array Creation

In [3]:
## np.array, np.zeros, np.ones, np.arange, np.linspace

# array
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a * 2)       # vectorized — no loop needed
print(a ** 2)
print(np.sum(a))
print(np.mean(a))

print("------------------------------")
# 2D array
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print(M.shape)     # (2, 3)
print(M[0])        # first row
print(M[:, 1])     # second column
print(M.T)         # transpose

print("------------------------------")
# Some matrises
print(np.zeros((3, 3)))
print((np.ones((2, 4))))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

print("------------------------------")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)
print(A * B)
print(A @ B)
print(np.linalg.det(A))
print(np.linalg.eig(A))

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
15
3.0
------------------------------
(2, 3)
[1 2 3]
[2 5]
[[1 4]
 [2 5]
 [3 6]]
------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
------------------------------
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


## Indexing & Reshaping

In [4]:
# Slicing, fancy indexing, reshape
a = np.array([1, 2, 3])
print(a + 10)

A = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
print(A + b)

x = np.array([[1],
              [2],
              [3]])
y = np.array([10, 20, 30])
print(x + y)


a = np.array([1, 2, 3])
print(a.shape)   # (3,)

M = np.array([[1, 2, 3],
              [4, 5, 6]])
print(M.shape)   # (2, 3)


x = np.array([1, 2, 3])
y = np.array([[1], [2], [3]])
print(x.shape)
print(y.shape)
print(x + y)

[11 12 13]
[[11 22 33]
 [14 25 36]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
(3,)
(2, 3)
(3,)
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


Shape intuition
> `a + 10` works because scalar behaves like shape ().

> `A + b` works because b is treated like [10, 20, 30] across each row.

> `x + y` gives a full 3 x 3 result because shapes `(3, 1)` and `(3,)` broadcast to `(3, 3)`.

> A 1D array like `[1, 2, 3]` has shape `(3,)`, meaning 3 elements in one line.

> A 2D array like `[[1, 2, 3], [4, 5, 6]]` has shape `(2, 3)`, meaning 2 rows and 3 columns.

> A 3D array would have three numbers in its shape tuple, one for each axis.



In [5]:
a = np.array([1, 2, 3])        # shape (3,)
b = np.array([[1, 2, 3]])      # shape (1, 3)
c = np.array([[1], [2], [3]])   # shape (3, 1)

print("a.T:", a.T)
print("b.T:", b.T)
print("c.T:", c.T)

a.T: [1 2 3]
b.T: [[1]
 [2]
 [3]]
c.T: [[1 2 3]]


> In NumPy, a vector is usually treated as a 1D array, while a matrix is explicitly 2D, so a, b, and c are intentionally different shapes.

> [1, 2, 3] in NumPy is a vector.

> [[1], [2], [3]] is a 3×1 column matrix.

> [[1, 2, 3]] is a 3×1 row matrix.

> NumPy treats a as a 1D vector, while b and c are 2D matrices with orientation, so transpose changes the 2D ones but leaves the 1D one unchanged.

> a.T stays [1 2 3].

> b.T becomes a column shape [[1], [2], [3]].

> c.T becomes a row shape [[1 2 3]]

## Operations & Broadcasting

In [6]:
## Arithmetic, broadcasting rules
# reshape
a = np.arange(1, 13)
print(a)
print(a.shape)

B = a.reshape(3, 4)
print(B)
print(B.shape)


# Slicing(np arr)
M =np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(M[0:2,1:3])
print(M[1, :])
print(M[:, 0])

# View
S = M[0:2, 1:3]
print("S:\n ", S)
S[0,0] = 999
print("S:\n", S)
print("M:\n", M)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[2 3]
 [5 6]]
[4 5 6]
[1 4 7]
S:
  [[2 3]
 [5 6]]
S:
 [[999   3]
 [  5   6]]
M:
 [[  1 999   3]
 [  4   5   6]
 [  7   8   9]]


## Linear Algebra

In [7]:
# dot product, matmul, np.linalg.inv, np.linalg.eig


## OR Practice — Cost Matrix

In [8]:
# Build a cost matrix, find min cost row/col
